### ISSUE TITLE
Proposal to support TimeFormat

### ISSUE THREAD

**Issue by k-kinzal** [cosmo0920/fluent-bit-go-s3#25]
#### Problem

The current path to save to S3 is `/[path prefix]/YYYYMMDD/HH`.
However, I wanted to save in [Hive format](https://docs.aws.amazon.com/athena/latest/ug/partitions.html#scenario-1-data-already-partitioned-and-stored-on-s3-in-hive-format), like`/[path prefix]/dt=YYYY-MM-DD`, in order to use AWS Athena.

So can we add an option like `TimeFormat` to format the date part of the path?

```
[Output]
    Name s3
    Match *
    AccessKeyID     yourawsaccesskeyid
    SecretAccessKey yourawssecretaccesskey
    Bucket          yourbucketname
    S3Prefix yours3prefixname
    TimeFormat dt=%Y-%m-%d
    Region us-east-1
    Compress gzip
```

The value of `TimeFormat` might be better to use Golang's format, such as `TimeFormat dt=2006-01-02`.

#### Steps to replicate

None.
This is feature request.

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and S3 plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* fluent-bit version
  * paste result of ``fluent-bit --version`` or ``td-agent-bin --version``
* fluent-bit-go-s3 version
  * paste boot log of fluent-bit or td-agent-bit

**Comment by k-kinzal** [comment]
I implemented it in Go's time format for reference.
https://github.com/k-kinzal/fluent-bit-go-s3/commit/28aa3d3e25df883a2e6726d11b2c9b8bca1493cd
This is the easiest implementation, but I doubt it's user-friendly.

**Comment by cosmo0920** [comment]
Hmm, it looks reasonable for me!

**Comment by k-kinzal** [comment]
@cosmo0920 
Thanks for taking a look at my proposal!
So I'll send you a PR in Go's time format.
