### ISSUE TITLE
Proposal: Matches with the fluent bit log format.

### ISSUE THREAD

**Issue by k-kinzal** [cosmo0920/fluent-bit-go-s3#33]
#### Problem

There is a difference in the output format between fluent bit and fluent bit go s3.

**fluent bit log**
```
[2020/04/13 09:41:04] [ info] [engine] started (pid=1)
```

**fluent bit go s3**
```
time="2020-04-13T09:41:04Z" level=info msg="[flb-go 0] Starting fluent-bit-go-s3: (version=0.7.0, branch=HEAD, revision=e8a6673)"
```

This is not a big problem, but it does complicate the parsing of the log.

So I would like to change the format of the log, how about that?

#### Steps to replicate

None.
This is feature request.

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and S3 plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* fluent-bit version
  * paste result of ``fluent-bit --version`` or ``td-agent-bin --version``
* fluent-bit-go-s3 version
  * paste boot log of fluent-bit or td-agent-bit

**Comment by cosmo0920** [comment]
fluent-bit-go-s3 uses logrus for logger.
logrus seems to support customizing logging format.
https://github.com/sirupsen/logrus#formatters
