### ISSUE TITLE
S3 output plugin is not loaded

### ISSUE THREAD

**Issue by Jamietsy820** [cosmo0920/fluent-bit-go-s3#43]
#### Problem
I have installed fluentd bit through package installation in EC2 server and planned to transfer log from EC2 instance to S3 using fluentd bit. But there is no s3 output plugin for fluentd bit by default, hence I followed the steps in the guideline to install s3 output plugin. But it failed to load the plugin.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/44184973/91411490-fc040f00-e87a-11ea-8c82-f8e0642511bc.png">

...

#### Steps to replicate
_Below is the configuration file:
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' optoin is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

[INPUT]
    Name        tail
    Path        /var/log/nginx/access_log

[OUTPUT]
    Name s3
    Match *
    AccessKeyID     XXXXX
    SecretAccessKey XXXXXX
    Bucket          fluentd-log
    S3Prefix        Logs/
    SuffixAlgorithm sha256
    Region          ap-southeast-1
    Compress        gzip_

#### Expected Behavior or What you need to ask
Fluentd bit should be able to transfer log to S3 bucket.

...

#### Using Fluentd and S3 plugin versions

* EC2 server - Ubuntu 18.04 LTS
* Used docker to install S3 plugin. 
* fluent-bit version
  * Fluent Bit v1.5.3
* fluent-bit-go-s3 version
  * latest version

**Comment by cosmo0920** [comment]
This is because the guideline *does not describe elementary level of loading shared object*.
I don't want to describe shared object loading mechanism on README.
Could you put out_s3.so into `LD_LIBRARY_PATH` or specify `-e` option to tell fluent-bit where out_s3.so is?

**Comment by Jamietsy820** [comment]
This is the command I run after the steps **make build-image** and 
docker run -it -e="FLUENT_BIT_ACCESS_KEY_ID=XXXXX" -e="FLUENT_BIT_SECRET_ACCESS_KEY=XXXXXX" -e="FLUENT_BIT_BUCKET_NAME=fluentd-log" -e="FLUENT_BIT_S3_PREFIX=Logs/" -e="FLUENT_BIT_REGION=ap-southeast-1" -e="FLUENT_BIT_SUFFIX_ALGORITHM=sha256" cosmo0920/fluent-bit-go-s3:latest

**Comment by cosmo0920** [comment]
docker run -it -e="FLUENT_BIT_ACCESS_KEY_ID=XXXXX" -e="FLUENT_BIT_SECRET_ACCESS_KEY=XXXXXX"  -e="FLUENT_BIT_BUCKET_NAME=fluent-bit-k8s" -e="FLUENT_BIT_S3_PREFIX=Logs/" -e="FLUENT_BIT_REGION=us-east-1" -e="FLUENT_BIT_SUFFIX_ALGORITHM=sha256" cosmo0920/fluent-bit-go-s3:v0.7.2-2.0

should handle out_s3.so:

```
Fluent Bit v1.5.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/08/27 08:42:38] [ info] [engine] started (pid=1)
[2020/08/27 08:42:38] [ info] [storage] version=1.0.5, initializing...
[2020/08/27 08:42:38] [ info] [s3operator] id = 0
[2020/08/27 08:42:38] [ info] [storage] in-memory
[2020/08/27 08:42:38] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/08/27 08:42:38] [ info] [flb-go 0] Starting fluent-bit-go-s3: (version=0.7.2, branch=master, revision=0c22775)
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin credential parameter = ''
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin accessKeyID parameter = 'A...V'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin secretAccessKey parameter = 'q...P'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin bucket parameter = 'fluent-bit-k8s'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin s3prefix parameter = 'Logs/'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin suffixAlgorithm parameter = 'sha256'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin region parameter = 'us-east-1'
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin compress parameter = ''
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin endpoint parameter = ''
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin autoCreateBucket parameter = ''
[2020/08/27 08:42:38] [ info] [flb-go 0] plugin timeZone parameter = ''
[2020/08/27 08:42:38] [ info] [sp] stream processor started
```

**Comment by Jamietsy820** [comment]
Is it possible to let it run in the background?

**Comment by cosmo0920** [comment]
You can use detached mode:
https://docs.docker.com/engine/reference/run/#detached--d

**Comment by Jamietsy820** [comment]
my input configuration as shown below:
[INPUT]
Name tail
Path /var/log/nginx/access_log

But the logs that pushed to S3 shown CPU metrics.
**{"system_p":0,"cpu0.p_cpu":0,"cpu0.p_user":0,"cpu0.p_system":0,"cpu_p":0,"user_p":0}
{"cpu0.p_user":0,"cpu0.p_system":0,"cpu_p":0,"user_p":0,"system_p":0,"cpu0.p_cpu":0}
{"user_p":0,"system_p":0,"cpu0.p_cpu":0,"cpu0.p_user":0,"cpu0.p_system":0,"cpu_p":0}
{"cpu0.p_system":0,"cpu_p":0,"user_p":0,"system_p":0,"cpu0.p_cpu":0,"cpu0.p_user":0}
{"cpu0.p_cpu":0,"cpu0.p_user":0,"cpu0.p_system":0,"cpu_p":0,"user_p":0,"system_p":0}**

Can advise on this?
Thank you.

**Comment by cosmo0920** [comment]
You should put your configuration into `docker/fluent-bit-s3.conf`.
See: https://github.com/cosmo0920/fluent-bit-go-s3/blob/master/Dockerfile#L15

And I don't want to modify this configuration into another settings.
This built image should be base image for k8s settings which is put under `docker` or helm templates which are put under `helm/fluent-bit`.

**Comment by cosmo0920** [comment]
And S3 output plugin is not loaded issue seems to be fixed.
Your issue should be docker related usage.
If you have further questions, please open an new issue.

**Comment by Jamietsy820** [comment]
Thank you.
