### ISSUE TITLE
When multiple outputs, only latest definition is valid

### ISSUE THREAD

**Issue by antennix** [cosmo0920/fluent-bit-go-s3#8]
#### Problem
The definition appears to be overwritten
Example:
```
[OUTPUT]
    Name s3
    Match           LogA
    AccessKeyID     ******
    SecretAccessKey ********
    Bucket          A
    S3Prefix        A
    Region          ap-northeast-1

[OUTPUT]
    Name s3
    Match           LogB
    AccessKeyID     ******
    SecretAccessKey ********
    Bucket          B
    S3Prefix        B
    Region          ap-northeast-1

````

Result:
    LogA →　Bucket B,S3Prefix B
    LogB →　Bucket B,S3Prefix B

Does anyone have the same problem?

**Comment by cosmo0920** [comment]
Multiple instance is not supported yet.

**Comment by yo-nakamura-mediba** [comment]
Got it.

**Comment by antennix** [comment]
I see. Thanks!

**Comment by cosmo0920** [comment]
Will be supported within a couple of days.

**Comment by cosmo0920** [comment]
I've created #9 to fix this issue.

Could you try it out, @antennix?

**Comment by cosmo0920** [comment]
Perhaps, are you also interested in the patch(#9), @yo-nakamura-mediba?

**Comment by antennix** [comment]
yeah multiple output function works correctly.
thank you!
